### PR TITLE
make opts accessable to mailer

### LINKED ISSUE #48: Pass a different host or _url options to mailer `magic_link_url`
I have a multi-tenant site and need to keep the host / subdomain from the request and pass it into the `magic_link_url` in the mailer somehow.

I made a monkey patch but maybe there is a better way to handle this - #49

With this you can do:
```ruby
resource&.send_magic_link(remember_me: create_params[:remember_me], opts: {host: request.host})
```

and in the mailer you can:
```ruby
magic_link_url(@resource, @scope_name => {email: @resource.email, token: @token, remember_me: @remember_me},
  host: @opts.dig(:opts)&.dig(:host) || Rails.application.config.action_mailer.default_url_options[:host]
)
```

### PR DESCRIPTION
**Pull request by iseth**
closes #48

### CODE REVIEW

**Comment by codespearhead** [comment]
There's a failing test:

```sh
290 /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:456:in
291 parse_stream': undefined method `parse' for #<Psych::Parser:0x0000555835987a28>
```

Can you install the following dependency and try again?

```sh
apt-get install -y libyaml-dev
```

**Comment by iseth** [comment]
I think if we rerun the failing tests it should work. Its working in main and i did not change anything that would make the effect `libyaml`.

**Comment by abevoelker** [comment]
Thanks for your contribution! :tada:  I merged this into master a long while ago, but only just released it with gem version 1.0.2. Took me a while to fix the build due to some family health issues - thanks for your patience

**Comment by iseth** [comment]
awesome. Ill update my gems to upstream thanks 👍

**Pull request merged**
